about/urls.py
from django.urls import path
from .views import AboutView


app_name = "about"
urlpatterns = [
    path('about/', AboutView.as_view(), name = "page"),
]

company/urls.py
from django.urls import path
from .views import CompanyDetailView, CompanyListView

app_name = "company"
urlpatterns = [
    path('companies/', CompanyListView.as_view(), name = "list_view"),
    path('companies/<slug:slug>', CompanyDetailView.as_view(), name = "detail_view"),
]

config/urls.py
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = []

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('',include('industries.urls')),
    path('',include('company.urls')),
    # path('',include('news.urls')),
    path('',include('about.urls')),
    path('',include('contact_us.urls')),
    path('rosetta/',include('rosetta.urls')),

    # prefix_default_language=False
)


if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact_us/urls.py
from django.urls import path
from .views import ContactUsView


app_name = "contact"
urlpatterns = [
    path('contact/', ContactUsView.as_view(), name = "page"),
]

home/urls.py
from django.urls import path
from .views import Index, SiteFooterView, SiteHeaderView

app_name = "page"
urlpatterns = [
    path('', Index.as_view(), name="home"),
    path('header/', SiteHeaderView.as_view(), name="head"),
    path('footer/', SiteFooterView.as_view(), name="foot"),
]

news/urls.py
from django.urls import path
from .views import NewsListView, NewsDetailView

app_name = "news"
urlpatterns = [
    path('news/', NewsListView.as_view(), name="list_view"),
    path('news/<slug:slug>', NewsDetailView.as_view(), name='detail_view'),
]

templates/base/shared/contact_sidebar.html
{% load i18n %}
<p>{% trans "Ehsan Group is a well-known brand with more than 50 years of brilliant history" %}</p>
<a href="{% url 'contact:page' %}">{% trans "Contact Us" %}</a>

templates/base/shared/footer.html
{% load static%}
{% load i18n %}
        <!-- Site Footer -->
        <footer class="industify_fn_footer">
            <div class="top_footer">
               <div class="top_footer_img" data-fn-bg-img="{% static 'img/footer/footer.webp' %}" style="background-image: url({% static 'img/footer/footer.webp' %});"></div>
               <!-- TRIPLE WIDGET -->
               <div class="footer_widget">
                  <div class="container">
                     <div class="inner">
                        <ul class="widget_area">
                           <li>
                              <div class="item">
                                 <div class="logo">
                                     <a href="{% url 'page:home' %}"><img src="{{ info.logo_light.url }}" alt=""></a>
                                 </div>
                                 <div class="textwidget">
                                     <p>{{ info.description }}</p>
                                 </div>
                              </div>
                           </li>
                           <!-- removed li -->
                           <!-- removed li -->
                           <li>
                              <div class="item">
                                  <div class="wid-title"><span>{% trans "Helpful Links" %}</span></div>
                                  <div class="widget_nav_menu">
                                      <ul class="menu">
                                        {% for link in info.links.all %}
                                        <li><a rel="nofollow" target="_blank" href="{{ link.link }}">{{ link.title }}</a></li>
                                        {% endfor %}
                                      </ul>
                                  </div>
                              </div>
                           </li>
                        </ul>
                     </div>
                  </div>
               </div>
               <!-- /TRIPLE WIDGET -->
            </div>
            <!-- BOTTOM -->
            <div class="footer_bottom">
               <div class="container">
                  <div class="footer_bottom_in">
                     <div class="bottom_widget">
                         <div class="widget_nav_menu">
                             <ul class="menu">
                                 <li><a href="{% url 'page:home' %}">{% trans "Home" %}</a></li>
                                 <li><a href="{% url 'about:page' %}">{% trans "About" %}</a></li>
                                 <li><a href="{% url 'industry:list_view' %}">{% trans "Industries" %}</a></li>
                                 {% comment %} <li><a href="{% url 'news:list_view' %}">{% trans "News" %}</a></li> {% endcomment %}
                                 <li><a href="{% url 'company:list_view' %}">{% trans "Company" %}</a></li>
                                 <li><a href="{% url 'contact:page' %}">{% trans "Contact" %}</a></li>
                             </ul>
                         </div>
                     </div>
                     <div class="footer_copyright" style="display: none;">
                         <p>© 1934 – <script>document.write(/\d{4}/.exec(Date())[0])</script> {% trans "Ehsan Group, LCC. All rights reserved. Design and developed by" %},
                             <a rel="nofollow" href="https://farzinshams.com" target="_blank">Farzin Shams</a>
                         </p>
                     </div>
                     <a class="industify_fn_totop" href="#">
                         <span class="top"></span>
                         <span class="text">{% trans "To Top" %}</span>
                     </a>
                  </div>
               </div>
            </div>
            <!-- /BOTTOM -->
         </footer>
        <!-- /Site Footer -->
    </div>
    <!-- /Wrapper -->
</div>
<!-- /Wrapper All -->

templates/base/shared/header.html
{% load static%}
{% load i18n %}
<div class="industify_fn_wrapper_all" {% if request.resolver_match.url_name == 'home' %} data-nav-skin="transdark"{% endif %}>
    <div class="industify_fn_wrapper">
        <!-- Header -->
        <div class="industify_fn_header">
            <!-- Header: Bottom Panel -->
            <div class="industify_fn_header">
                <!-- Header: Bottom Panel -->
                <div class="header_inner">
                    <div class="menu_logo">
                        <a href="{% url 'page:home' %}">
                            <img class="desktop_logo" src="{{ info.logo_light.url }}" alt="Industry HTML Template">
                            <img class="desktop_logo_dark" src="{{ info.logo_dark.url }}" alt="Industry HTML Template">
                        </a>
                    </div>
                    <div class="menu_nav">
                        <ul class="industify_fn_main_nav vert_nav">
                            <li>
                                <a href="{% url 'page:home' %}">{% trans "Home" %}</a>
                            </li>
                            <li>
                                <a href="{% url 'about:page' %}">{% trans "About" %}</a>
                            </li>
                            <li class="menu-item-has-children">
                                <a href="{% url 'industry:list_view' %}">{% trans "Industries" %}</a>
                                <ul class="sub-menu">
                                    {% for item in industry %}
                                    <li><a href="{% url 'industry:detail_view' item.slug %}">{{ item.title }}</a></li>
                                    {% endfor %}
                                </ul>
                            </li>
                            {% comment %} <li>
                                <a href="{% url 'news:list_view' %}">{% trans "News" %}</a>
                            </li> {% endcomment %}
                            <li>
                                <a href="{% url 'company:list_view' %}">{% trans "Company" %}</a>
                            </li>
                            <li>
                                <a href="{% url 'contact:page' %}">{% trans "Contact" %}</a>
                            </li>
                            {% if request.LANGUAGE_CODE == 'fa' %}
                                <li class="menu-item-has-children">
                                    <a href="#">{% trans "Career" %}</a>
                                    <ul class="sub-menu">
                                        <li><a target="_blank" href="https://career.ehsan.group">{% trans "Ehsan Management Group" %}</a></li>
                                        <li><a target="_blank" href="https://job.ehsan.group">{% trans "Hoonam Trade" %}</a></li>
                                    </ul>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                    <div class="toll_free_lang">
                        <div class="lang_switcher language-switch">
                            {% if request.LANGUAGE_CODE == 'fa' %}
                                <span class="click">En</span>
                                <ul>
                                    <li><a href="#" class="en" id="switch-language"><span>En</span></a></li>
                                    <li class="active"><span>Fa</span></li>
                                </ul>
                            {% else %}
                                <span class="click">Fa</span>
                                <ul>
                                    <li class="active"><span>En</span></li>
                                    <li><a href="#" class="fa" id="switch-language"><span>Fa</span></a></li>
                                </ul>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <!-- /Header: Bottom Panel -->
            </div>
            <!-- /Header: Bottom Panel -->
        </div>
                <!-- /Header -->

                <!-- Mobile Menu -->
                <div class="industify_fn_mobilemenu_wrap">
        <!-- LOGO & HAMBURGER -->
        <div class="logo_hamb">
            <div class="in">
                <div class="menu_logo">
                    <a href="{% url 'page:home' %}"><img src="{{ info.logo_light.url }}" alt="Industry HTML Template"></a>
                </div>
                <div class="hamburger hamburger--collapse-r">
                    <div class="hamburger-box">
                    <div class="hamburger-inner"></div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /LOGO & HAMBURGER -->
        <!-- MOBILE DROPDOWN MENU -->
        <div class="mobilemenu">
            <div>
                <ul class="vert_menu_list">
                    <li>
                        <a href="{% url 'page:home' %}">{% trans "Home" %}</a>
                    </li>
                    <li>
                        <a href="{% url 'about:page' %}">{% trans "About" %}</a>
                    </li>
                    <li class="menu-item-has-children">
                        <a href="{% url 'industry:list_view' %}">{% trans "Industries" %}</a>
                        <ul class="sub-menu">
                            {% for item in industry %}
                                <li><a href="{% url 'industry:detail_view' item.slug %}">{{ item.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    {% comment %} <li>
                        <a href="{% url 'news:list_view' %}">{% trans "News" %}</a>
                    </li> {% endcomment %}
                    <li>
                        <a href="{% url 'company:list_view' %}">{% trans "Company" %}</a>
                    </li>
                    <li>
                        <a href="{% url 'contact:page' %}">{% trans "Contact" %}</a>
                    </li>
                    {% if request.LANGUAGE_CODE == 'fa' %}
                        <li class="menu-item-has-children">
                            <a href="#">{% trans "Career" %}</a>
                            <ul class="sub-menu">
                                <li><a target="_blank" href="https://career.ehsan.group">{% trans "Career" %}</a></li>
                                <li><a target="_blank" href="https://job.ehsan.group">{% trans "Job" %}</a></li>
                            </ul>
                        </li>
                    {% endif %}
                </ul>
            </div>
            <div class="toll_free_lang">
                <div class="lang_switcher language-switch">
                    {% if request.LANGUAGE_CODE == 'fa' %}
                        <span class="click">En</span>
                        <ul>
                            <li><a href="#" class="en" id="switch-language"><span>En</span></a></li>
                            <li class="active"><span>Fa</span></li>
                        </ul>
                    {% else %}
                        <span class="click">Fa</span>
                        <ul>
                            <li class="active"><span>En</span></li>
                            <li><a href="#" class="fa" id="switch-language"><span>Fa</span></a></li>
                        </ul>
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- /MOBILE DROPDOWN MENU -->
        </div>
        <!-- /Mobile Menu -->

templates/base/shared/preloader.html
<!-- Preloader -->
<div id="industify-fn-loader">
    <div class="fn_loader"></div>
    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>
</div>
<!-- /Preloader -->