config/urls.py
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = []

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('',include('industries.urls')),
    path('',include('company.urls')),
    # path('',include('news.urls')),
    path('',include('about.urls')),
    path('',include('contact_us.urls')),
    path('rosetta/',include('rosetta.urls')),

    # prefix_default_language=False
)


if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import Index, SiteFooterView, SiteHeaderView

app_name = "page"
urlpatterns = [
    path('', Index.as_view(), name="home"),
    path('header/', SiteHeaderView.as_view(), name="head"),
    path('footer/', SiteFooterView.as_view(), name="foot"),
]

industries/urls.py
from django.urls import path
from .views import IndustryListView, IndustryDetailView

app_name = "industry"
urlpatterns = [
    path('industries/', IndustryListView.as_view(), name="list_view"),
    path('industries/<slug:slug>', IndustryDetailView.as_view(), name='detail_view'),
]

industries/models.py
from django.db import models
from django.utils import timezone
from tinymce.models import HTMLField
from django.utils.html import format_html

# Create your models here.
class Industry(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Publish')
    )
    title = models.CharField(max_length=300)
    slug = models.SlugField(max_length=200, unique=True)
    description = HTMLField()
    image = models.ImageField(upload_to='industry')
    image_thumbnail = models.ImageField(upload_to='industry/thumbs')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    keywords = models.CharField(max_length=300, null=True)
    seo_description = models.TextField(null=True)

    def __str__(self):
        return self.title
    

    def thumbnail_tag(self):
        return format_html(
            "<img width=100 height=75 style='border-radius: 5px;' src='{}'>".format(self.image_thumbnail.url))

industries/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Industry


# Create your views here.
class IndustryListView(ListView):
    queryset = Industry.objects.filter(status="p").order_by('-publish')
    model = Industry
    template_name = 'industry_list.html'
    context_object_name = 'industry'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest'] = Industry.objects.filter(status="p").order_by('-publish')[:5]
        return context

class IndustryDetailView(DetailView):
    model = Industry
    context_object_name = 'industry'
    queryset = Industry.objects.filter(status='p')
    template_name = 'industry_detail.html'

industries/templates/industry_detail.html
{% extends 'base/main_base.html' %}
{% load thumbnail %}
{% load i18n %}
{% load static %}
{% block title %}{% trans "Ehsan Group" %} | {{ industry.title }}{% endblock title %}
{% block description %}{{ industry.description|striptags|truncatewords:30 }}{% endblock description %}
{% block content %}
    <!-- Page Title -->
    <div class="industify_fn_pagetitle">
        <div class="container">
            <div class="title_holder">
                <h3>{{ industry.title }}</h3>
                <div class="industify_fn_breadcrumbs">
                    <ul>
                        <li><a href="{% url 'page:home' %}" title="Home">{% trans "Home" %}</a></li>
                        <li class="separator"><span></span></li>
                        <li><span class="bread-current"><a href="{% url 'industry:list_view' %}" >{% trans "Industry" %}</a></span></li>
                        <li class="separator"><span></span></li>
                        <li><span class="bread-current">{{ industry.title }}</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- /Page Title -->
    <div class="industify_fn_blog_full">
        <div class="container">
            <ul class="industify_fn_postlist">
                <li>
                    <div class="post has-post-thumbnail">
                        <div class="img_holder">
                            <a href="#">
                                {% thumbnail industry.image "1170x600" as im %}
                                    <img src="{{ im.url }}" alt="{{ industry.slug }}">
                                {% endthumbnail %}
                            </a>
                            <span class="shape1"></span><span class="shape2" style="border-left-width: 1070px;"></span>
                        </div>
                        <div class="content_holder">
                            <div class="title">
                                <h3>
                                    <a href="#">{{ industry.title }}</a>
                                </h3>
                            </div>
                            <div class="excerpt_holder">
                                {{ industry.description|safe }}
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}

industries/templates/industry_list.html
{% extends 'base/main_base.html' %}
{% load thumbnail %}
{% load i18n %}
{% load static %}
{% block title %}{% trans "Ehsan Group | Industries" %}{% endblock title %}
{% block content %}
<!-- Page Title -->
<div class="industify_fn_pagetitle">
    <div class="container">
        <div class="title_holder">
            <h3>{% trans "Industries" %}</h3>
            <div class="industify_fn_breadcrumbs">
                <ul>
                    <li><a href="{% url 'page:home' %}" title="Home">{% trans "Home" %}</a></li>
                    <li class="separator"><span></span></li>
                    <li><span class="bread-current">{% trans " Industries" %}</span></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- /Page Title -->
<!-- Sidebar Page -->
<div class="industify_fn_sidebarpage">
    <div class="container">
        <div class="s_inner">
            <!-- Main Sidebar: Left -->
            <div class="industify_fn_leftsidebar">
                <ul class="industify_fn_service_list">
                    {% for item in industry %}
                    <li>
                        <div class="item">
                            <div class="item_in">
                                <div class="img_holder">
                                    {% thumbnail item.image "500x500" as im %}
                                        <div class="img_abs" data-fn-bg-img="{{ im.url }}" style="background-image: url({{ im.url }});"></div>
                                    {% endthumbnail %}
                                    <a href="{% url 'industry:detail_view' item.slug %}"></a>
                                </div>
                                <div class="title">
                                    <h3><a href="{% url 'industry:detail_view' item.slug %}">{{ item.title }}</a></h3>
                                    <p>{{ item.seo_description|safe }}</p>
                                </div>
                                <div class="read_more">
                                    <a href="{% url 'industry:detail_view' item.slug %}">{% trans "Read More" %}</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
                <div class="center">
                    <ul class="page">
                        {% for page in paginator.page_range %}
                        <li><a class="page-btn{% if page == request.GET.page|default:1|add:0 %} active-page{% endif %}" href="?page={{ page }}">{{ forloop.counter }}</a></li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="clearfix"></div>
            </div>
            <!-- /Main Sidebar: Left -->
            <!-- Main Sidebar: Right -->
            <div class="industify_fn_rightsidebar">
                <!-- Service List -->
                <div class="service_list_as_function">
                    <div class="title">
                        <h3>{% trans "Sub-industries" %}</h3>
                    </div>
                    <div class="list_holder">
                        <ul>
                            {% for each in latest %}
                                <li><a href="{% url 'industry:detail_view' each.slug %}">{{ each.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <!-- /Service List -->
                <!-- Get Sidebar -->
                <div class="industify_fn_sidebar">
<div class="industify_fn_sidebar_in">

<div class="widget_block">
    <div class="industify_fn_widget_estimate">
        <div class="img_holder">
            <span class="helper1" style="border-left-width: 80px; border-top-width: 55px;"></span>
            <span class="helper2" style="border-right-width: 220px; border-top-width: 55px;"></span>
            <span class="helper3" style="border-left-width: 80px; border-top-width: 80px;"></span>
            <span class="helper4" style="border-right-width: 220px; border-top-width: 80px;"></span>
            <span class="helper5" style="border-left-width: 80px; border-top-width: 80px;"></span>
            <span class="helper6" style="border-right-width: 220px; border-top-width: 80px;"></span>
            <div class="abs_img" data-fn-bg-img="{% static 'img/sidebar.jpg'%}" style="background-image: url({% static 'img/sidebar.jpg'%});"></div>
        </div>
        <div class="bfwe_inner">
            {% include 'base/shared/contact_sidebar.html'%}
        </div>
    </div>
</div>

</div>
</div>
                <!-- /Get Sidebar -->


            </div>
            <!-- Main Sidebar: Right -->

        </div>
    </div>
</div>
<!-- /Sidebar Page -->
{% endblock %}