config/urls.py
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = []

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('',include('industries.urls')),
    path('',include('company.urls')),
    # path('',include('news.urls')),
    path('',include('about.urls')),
    path('',include('contact_us.urls')),
    path('rosetta/',include('rosetta.urls')),

    # prefix_default_language=False
)


if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import Index, SiteFooterView, SiteHeaderView

app_name = "page"
urlpatterns = [
    path('', Index.as_view(), name="home"),
    path('header/', SiteHeaderView.as_view(), name="head"),
    path('footer/', SiteFooterView.as_view(), name="foot"),
]

news/urls.py
from django.urls import path
from .views import NewsListView, NewsDetailView

app_name = "news"
urlpatterns = [
    path('news/', NewsListView.as_view(), name="list_view"),
    path('news/<slug:slug>', NewsDetailView.as_view(), name='detail_view'),
]

news/models.py
from django.db import models
from django.utils import timezone
from account.models import User
from tinymce.models import HTMLField



class NewsManager(models.Manager):
    def published(self):
        return self.filter(status='p')


class Category(models.Model):
    title = models.CharField(max_length=300)
    slug = models.SlugField(max_length=200, unique=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class Tags(models.Model):
    title = models.CharField(max_length=300)
    slug = models.SlugField(max_length=200, unique=True)
    status = models.BooleanField(default=True)


    def __str__(self):
        return self.title


class News(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Publish')
    )
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='news')
    title = models.CharField(max_length=300)
    slug = models.SlugField(max_length=200, unique=True)
    category = models.ManyToManyField(Category, related_name='news')
    tags = models.ManyToManyField(Tags, related_name='news', blank=True)
    description = HTMLField()
    image = models.ImageField(upload_to='news')
    thumbnail = models.ImageField(upload_to='news/thumb', null=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    keywords = models.CharField(max_length=300, null=True)
    seo_description = models.TextField(null=True)


    def __str__(self):
        return self.title

    objects = NewsManager()

news/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import News

# Create your views here.
class NewsListView(ListView):
    queryset = News.objects.published()
    model = News
    template_name = 'news_list.html'
    context_object_name = 'news'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest'] = News.objects.published()[:5]
        return context

class NewsDetailView(DetailView):
    model = News
    context_object_name = 'news'
    queryset = News.objects.published()
    template_name = 'news_detail.html'

news/templates/news_detail.html
{% extends 'base/main_base.html' %}
{% load thumbnail %}
{% load i18n %}
{% load static %}
{% block title %}{% trans "Ehsan Group" %} | {{ news.title }}{% endblock title %}
{% block description %}{{ news.description|striptags|truncatewords:30 }}{% endblock description %}
{% block content %}
<!-- Page Title -->
<div class="industify_fn_pagetitle">
    <div class="container">
        <div class="title_holder">
            <h3>{% trans "News" %}</h3>
            <div class="industify_fn_breadcrumbs">
                <ul>
                    <li><a href="{% url 'page:home' %}" title="Home">{% trans "Home" %}</a></li>
                    <li class="separator"><span></span></li>
                    <li><span class="bread-current"><a href="{% url 'news:list_view' %}" >{% trans "News" %}</a></span></li>
                    <li class="separator"><span></span></li>
                    <li><span class="bread-current">{{ news.title }}</span></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- /Page Title -->
<div class="industify_fn_blog_full">
    <div class="container">
        <ul class="industify_fn_postlist">
            <li>
                <div class="post has-post-thumbnail">
                    <div class="time"><span></span>
                        <h3>{{ news.publish|date:"d" }}</h3><h5>{{ news.publish|date:"M" }}</h5><h5>{{ news.publish|date:"Y" }}</h5></div>
                    <div class="img_holder">
                        <a href="#">
                            {% thumbnail news.image "1170x600" as im %}
                                <img src="{{ im.url }}" alt="{{ news.title }}"/>
                            {% endthumbnail %}
                        </a>
                        <span class="shape1"></span><span class="shape2"></span>
                    </div>
                    <div class="content_holder">
                        <div class="title">
                            <h3><a href="#">{{ news.title }}</a></h3>
                        </div>
                        <div class="excerpt_holder">
                            {{ news.description|safe }}
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>
{% endblock %}

news/templates/news_list.html
{% extends 'base/main_base.html' %}
{% load thumbnail %}
{% load i18n %}
{% load static %}
{% block title %}{% trans "Ehsan Group | News" %}{% endblock title %}
{% block content %}
<!-- ALL PAGES -->
<div class="industify_fn_all_pages">
    <div class="industify_fn_all_pages_inner">
        <!-- WITH SIDEBAR -->
        <div class="industify_fn_sidebarpage">
            <div class="container">
                <!-- PAGE TITLE -->
                <div class="industify_fn_pagetitle">
                    <div class="title_holder">
                        <h3>{% trans "News" %} &#038; {% trans "Articles" %}</h3>
                        <div class="industify_fn_breadcrumbs">
                            <ul id="breadcrumbs" class="breadcrumbs">
                                <li class="item-home"><a class="bread-link bread-home"
                                        href="{% url 'page:home' %}"
                                        title="Home">{% trans "Home" %}</a></li>
                                <li class="separator separator-home"> <span></span> </li>
                                <li class="item-current item-72"><span
                                        class="bread-current bread-72"> {% trans "News" %} &#038; {% trans "Articles" %}</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /PAGE TITLE -->
                <div class="s_inner">
                    <div class="industify_fn_leftsidebar"
                        style=padding-top:70px;padding-bottom:147px;>
                        <ul class="industify_fn_postlist">
                            {% for item in news %}
                            <li>
                                <div class="post has-post-thumbnail">
                                    <div class="time"><span></span>
                                        <h3>{{ item.publish|date:"d" }}</h3><h5>{{ item.publish|date:"M" }}</h5><h5>{{ item.publish|date:"Y" }}</h5></div>
                                    <div class="img_holder">
                                        <a href="{% url 'news:detail_view' item.slug %}">
                                            {% thumbnail item.image "820x461" as im %}
                                            <img src="{{ im.url }}" alt="{{ item.title }}"/>
                                            {% endthumbnail %}
                                        </a>
                                        <span class="shape1"></span><span class="shape2"></span>
                                    </div>
                                    <div class="content_holder">
                                        <div class="info_holder">
                                            <p>
                                                <span class="t_author">{% trans "By" %} <a href="#"
                                                                             target="_blank">{% trans "Ehsan Group" %}</a></span>
                                                <span class="t_category">{% for cat in item.category.all %} {{ cat.title }}{% endfor %}</span>
                                            </p>
                                        </div>
                                        <div class="title">
                                            <h3>{{ item.title }}</h3>
                                        </div>
                                        <div class="excerpt_holder">
                                            {{ item.description|safe|truncatewords:40 }}
                                        </div>
                                        <div class="read_holder">
                                            <p><a href="{% url 'news:detail_view' item.slug %}">{% trans "Read More" %}</a></p>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                        <div class="center">
                            <ul class="page">
                                {% for page in paginator.page_range %}
                                <li><a class="page-btn{% if page == request.GET.page|default:1|add:0 %} active-page{% endif %}" href="?page={{ page }}">{{ forloop.counter }}</a></li>
                            {% endfor %}
                            </ul>
                        </div>
                    </div>
              <!-- Main Sidebar: Right -->
            <div class="industify_fn_rightsidebar">
                <!-- Service List -->
                <div class="service_list_as_function">
                    <div class="title">
                        <h3>{% trans "Latest News" %}</h3>
                    </div>
                    <div class="list_holder">
                        <ul>
                            {% for each in latest %}
                                <li><a href="{% url 'news:detail_view' each.slug %}">{{ each.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <!-- /Service List -->

                <!-- Get Sidebar -->
                <div class="industify_fn_sidebar">
<div class="industify_fn_sidebar_in">

<div class="widget_block">
    <div class="industify_fn_widget_estimate">
        <div class="img_holder">
            <span class="helper1" style="border-left-width: 80px; border-top-width: 55px;"></span>
            <span class="helper2" style="border-right-width: 220px; border-top-width: 55px;"></span>
            <span class="helper3" style="border-left-width: 80px; border-top-width: 80px;"></span>
            <span class="helper4" style="border-right-width: 220px; border-top-width: 80px;"></span>
            <span class="helper5" style="border-left-width: 80px; border-top-width: 80px;"></span>
            <span class="helper6" style="border-right-width: 220px; border-top-width: 80px;"></span>
            <div class="abs_img" data-fn-bg-img="{% static 'img/sidebar.jpg'%}" style="background-image: url({% static 'img/sidebar.jpg'%});"></div>
        </div>
        <div class="bfwe_inner">
            {% include 'base/shared/contact_sidebar.html'%}
        </div>
    </div>
</div>

</div>
</div>
                <!-- /Get Sidebar -->


            </div>
            <!-- Main Sidebar: Right -->
                </div>
            </div>
        </div>
        <!-- /WITH SIDEBAR -->

    </div>
</div>
<!-- /ALL PAGES -->
{% endblock %}